# Generated by Django 3.0.5 on 2020-05-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(verbose_name='data da compra')),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste_rifaki.Anunciante')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Anuncio')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste_rifaki.Comprador')),
            ],
        ),
    ]
