# Generated by Django 3.0.5 on 2020-05-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste_rifaki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='anunciante',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='anuncio',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='comprador',
        ),
        migrations.DeleteModel(
            name='Anunciante',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Comprador',
        ),
    ]
