# Generated by Django 3.0.5 on 2020-05-16 17:22

import cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_anuncio_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem1',
            field=models.ImageField(blank=True, upload_to=cadastro.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.DecimalField(decimal_places=2, default='00,00', max_digits=6),
        ),
    ]
