# Generated by Django 3.0.5 on 2020-05-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20200516_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='ano_fabricacao',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.DecimalField(decimal_places=2, default='00,00', max_digits=6),
        ),
    ]
