# Generated by Django 3.0.5 on 2020-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
