# Generated by Django 3.0.5 on 2020-05-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerodasorte',
            name='numero_escolhido',
            field=models.IntegerField(),
        ),
    ]
