# Generated by Django 3.0.5 on 2020-06-02 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0002_auto_20200527_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_registro', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comprador_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL)),
                ('numero_vendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.NumeroDaSorte')),
                ('vendedor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
